# Generated by Django 5.2.3 on 2025-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0002_receita_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='cover',
            field=models.ImageField(upload_to='receitasapp/cover/%Y/%m/%d/'),
        ),
    ]
