# Generated by Django 5.2.3 on 2025-07-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0003_alter_receita_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitasapp.category'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='receitasapp/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
